# Generated by Django 3.0a1 on 2019-09-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('width', models.IntegerField()),
            ],
        ),
    ]
