# Generated by Django 3.0a1 on 2019-09-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='id',
        ),
        migrations.AlterField(
            model_name='documentation',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
